[links]
zed = { source = "zed", target = "~/.config/zed" }
nvim = { source = "nvim", target = "~/.config/nvim" }
nvchad = { source = "nvchad", target = "~/.config/nvchad" }
fish = { source = "fish", target = "~/.config/fish" }
claude = { source = "claude", target = "~/.config/claude" }
